import fs from 'node:fs';
import nodePath from 'node:path';
import { argv, cwd } from 'node:process';

const args = argv.slice(2);

const isProd = argv.includes('--prod');
const isDev = !isProd;

const pathSrc = './src';

let pathDist = '../view';
const distIndex = args.indexOf('--dist');
if (distIndex !== -1 && distIndex + 1 < args.length) {
  pathDist = args[distIndex + 1];
}

const packageData = JSON.parse(fs.readFileSync('./package.json'));

const absPath = {
  dist: nodePath.resolve(cwd(), pathDist),
  src: nodePath.resolve(cwd(), pathSrc),
  font: nodePath.resolve(cwd(), `${pathSrc}/font`),
  img: nodePath.resolve(cwd(), `${pathSrc}/img`),
  js: nodePath.resolve(cwd(), `${pathSrc}/js`),
  php: nodePath.resolve(cwd(), `${pathSrc}/php`),
  phpModule: nodePath.resolve(cwd(), `${pathSrc}/php-module`),
  public: nodePath.resolve(cwd(), `${pathSrc}/public`),
  sass: nodePath.resolve(cwd(), `${pathSrc}/sass`),
  template: nodePath.resolve(cwd(), `${pathSrc}/template`),
};

const path = {
  dist: pathDist,
  src: pathSrc,

  // TODO all forders except src
  del: pathDist,

  font: {
    src: `${pathSrc}/font/**/*.{woff2,woff,svg,ttf,eot}`,
    watch: `${pathSrc}/font/**/*.{woff2,woff,svg,ttf,eot}`,
    dist: `${pathDist}/asset/font`,
  },

  img: {
    src: `${pathSrc}/img/**/*.*`,
    watch: `${pathSrc}/img/**/*.*`,
    dist: `${pathDist}/asset/img`,
  },

  js: {
    src: `${pathSrc}/js/*.js`,
    watch: `${pathSrc}/js/**/*.js`,
    dist: `${pathDist}/asset/js`,
  },

  php: {
    src: `${pathSrc}/php/**/*.{php,ini,json,sql}`,
    watch: `${pathSrc}/php/**/*.{php,ini,json,sql}`,
    dist: pathDist,
  },

  phpModule: {
    src: `${pathSrc}/php-module/**/*.{php,ini,json,sql}`,
    watch: `${pathSrc}/php-module/**/*.{php,ini,json,sql}`,
    dist: `${pathDist}/..`,
  },

  public: {
    src: `${pathSrc}/public/**/*.*`,
    watch: `${pathSrc}/public/**/*.*`,
    dist: `${pathDist}/asset`,
  },

  sass: {
    src: `${pathSrc}/sass/*.{sass,scss}`,
    watch: `${pathSrc}/sass/**/*.{sass,scss}`,
    dist: `${pathDist}/asset/css`,
  },
};

const plugin = {
  // DEL
  del: {
    force: true,
  },

  // HTML
  htmlmin: {
    collapseWhitespace: true,
    includeAutoGeneratedTags: false,
    minifyCSS: true,
    minifyJS: true,
    removeComments: true,
  },
  versionNumber: {
    value: packageData.version || '%MDS%',
    append: {
      key: 'v',
      to: 'all',
    },
  },

  // IMAGE
  imagemin: {
    gifsicle: {
      optimizationLevel: 1,
      interlaced: false,
    },
    optipng: {
      optimizationLevel: 5,
    },
    mozjpeg: {
      quality: 75, progressive: true,
    },
    pngquant: {
      quality: [0.7, 0.9],
      speed: 7,
    },
    svgo: {
      plugins: [
        {
          name: 'removeViewBox',
          active: false,
        },
        {
          name: 'convertShapeToPath',
          active: false,
        },
        {
          name: 'convertEllipseToCircle',
          active: false,
        },
      ],
    },
  },

  // CSS
  sass: {
    includePaths: ['node_modules'],
  },
  autoprefixer: {
    cascade: !isProd,
    grid: false,
  },
  cssnano: {
    preset: [
      'default',
      {
        discardComments: {
          removeAll: true,
        },
      },
    ],
  },

  // JS
  terser: {
    mangle: true,
    keep_classnames: true,
    keep_fnames: false,
    ie8: false,
  },
};

export {
  isProd,
  isDev,
  packageData,
  absPath,
  path,
  plugin,
};
